# Generated by Django 3.0.8 on 2020-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('COL', 'Collectibles'), ('BOK', 'Books'), ('ELE', 'Electronics'), ('FAS', 'Fashion'), ('HOM', 'Home and Garden'), ('AUT', 'Auto parts'), ('MUS', 'Musical instruments'), ('SPO', 'Sporting goods'), ('TOY', 'Toys and Hobbies'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
